export const AUTHORIZATION_TOKEN = 'AUTHORIZATION_TOKEN'
export const AUTHORIZATION_CLIENTE = 'AUTHORIZATION_CLIENTE'
export const AUTHORIZATION_ROLES = 'AUTHORIZATION_ROLES'
export const LANGUAGE_DEFINITION = "LANGUAGE_DEFINITION"